### PR TITLE
Fixes for build failures

### PR DESCRIPTION
**Pull request by yaaama**
I was trying to build this but it failed first due to an implicit function error? and then because of an incompatible cast. 

It is now building on my machine but I haven't done any thorough testing, however the functionality seems to be fine.

Hopefully I haven't made any major oversights

Thank you,

### CODE REVIEW

**Comment by agvxov** [comment]
Interesting.
Both of should be only warnings under gcc, while apparently clang doesn't work at all as it has a different interface for compiled headers (~~this is something I'm going to fix, hopefully sooner than later~~ done now).

That said, the include is fair, however `char * found_caller` is actually, *just* a bool because of a combination legacy reasons and all search functions sharing a common signature now.
This will be fixed as soon as I work the ctags branch to a mergeable state, but its something that has been going slowly because I have to unroll copious amounts of global state to get there.
Point is, `findcalledby` uses NULL for false and 0x01 for true, it doesn't manage any actual memory, so there is no need for a `strdup()`.

Would you be so kind to open an Issue with the compile errors and your compiler specs?

**Comment by agvxov** [comment]
Never mind, I looked into it, surely it was clang, right?
Not sure how you managed to build it without modifying the Makefile.

With c53919efcf789f1c1fc8024b8b28d588a8f95e70 it seems to be working.
Hopefully it does for you too.

**Comment by yaaama** [comment]
> Interesting. Both of should be only warnings under gcc, while apparently clang doesn't work at all as it has a different interface for compiled headers (~this is something I'm going to fix, hopefully sooner than later~ done now).

Evening,
I rebuilt it and it is now working on my machine. Thank you. 

> That said, the include is fair, however `char * found_caller` is actually, _just_ a bool because of a combination legacy reasons and all search functions sharing a common signature now. This will be fixed as soon as I work the ctags branch to a mergeable state, but its something that has been going slowly because I have to unroll copious amounts of global state to get there. Point is, `findcalledby` uses NULL for false and 0x01 for true, it doesn't manage any actual memory, so there is no need for a `strdup()`.

Ahhh okay. I was unfamiliar with the codebase so I did not know whether the value was useful or not, hence the `strdup`

> Never mind, I looked into it, surely it was clang, right?
> Not sure how you managed to build it without modifying the Makefile.

I don't think `clang` is the default compiler on my system. I didn't fiddle around with the Makefile so I am not entirely sure what happened for it to fail like that. But its resolved now so it probably does not need any further thought.

Are you looking for any any help on the project? I'd like to lend a hand if I'm able to provide any value, this kind of project is quite valuable.

Thanks again & I will close this.

**Comment by agvxov** [comment]
@yaaama
Thanks for bringing the issue to my attention.

> Are you looking for any any help on the project? I'd like to lend a hand if I'm able to provide any value, this kind of project is quite valuable.

Sounds nice, I have thrown you an email regarding it, for further discussion.

**Pull request closed without merging**
